# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Auto Create UnsafeList

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run Shell
      run: python main.py
    - name: Set current date as env variable
      run: echo "now=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
    - name: Pushes file
      uses: Jason2866/copy_file_to_another_repo_action@http408_fix
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'unsafelist'
        destination_repo: 'HoshizoraProject/OpenData'
        user_email: '<>'
        user_name: 'YueyuHoshizora-BOT'
        commit_message: "Auto Update File At ${{ env.now }} UTC" 
